### ISSUE TITLE
本番では動かない問題について

### ISSUE THREAD

**Issue by kaaaaaaaaaaai** [ookam/docker_ngx_small_light#1]
@ookam 
別の問題だったらすいません😭

ポートが指定されてない感じがしますが
```
docker run -p 80:80 docker_ngx_small_light
```
で起動して設定したドメインにアクセスしたらどうでしょうか？

EC2立ててIPでアクセスしたらリサイズできるのを確認しました😄

**Comment by ookam** [comment]
@kaaaaaaaaaaai できた！！！！！！！！！！！！！！！天才！！！！！！！！！！！！！！！！！！！ありがとうございます！！！！！！！！！！！！！！！！！！
